name: Java CI and Docker Publish

on:
  push:
    branches: [ "main" ]

env:
  APP_NAME: "testmain"
  JAR_NAME: "app.jar"

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # ¡NECESARIO PARA PUBLICAR PAQUETES!

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build application
      run: |
        chmod +x gradlew
        ./gradlew clean bootJar
        ls -la build/libs/

    - name: Run tests
      run: ./gradlew test
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        # Convertir nombres a minúsculas
        OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        APP_NAME_LOWER=$(echo "${{ env.APP_NAME }}" | tr '[:upper:]' '[:lower:]')

        # Construir y publicar imagen
        docker buildx build \
          --tag ghcr.io/$OWNER_LOWER/$APP_NAME_LOWER:latest \
          --tag ghcr.io/$OWNER_LOWER/$APP_NAME_LOWER:${{ github.sha }} \
          --push .
      shell: bash
